### ISSUE TITLE
SSG Support

### ISSUE THREAD

**Issue by fitzage** [doublethreedigital/social-shots#5]
### What would you like to see added?

I don't even know if this is possible the way this is using puppeteer, but it would be sweet if this could work with the Statamic SSG.

### Is there a workaround you can use in the meantime?

Doesn't seem to be.

### Priority wise - where's this feature for you?

This is sort of a blocker for me/this project.

**Comment by duncanmcclean** [comment]
Yeah, right now Social Shots is pretty dumb and does it when the page loads. 

I'm planning on rewriting it (well, I have rewritten it but not tested it yet) so it'll generate them when entries are created/updated. I imagine it wouldn't be that hard to add SSG support at that point.

**Comment by duncanmcclean** [comment]
Thanks for reminding me about this addon - almost forgot it existed 😅 !

Just finished the re-write and tagged a release (see [v1.0.0](https://github.com/doublethreedigital/social-shots/releases/tag/v1.0.0)). You can use the `php please social-shots:warm` command to generate social images for all your entries. I'd recommend running it before you generate your static site.
